### ISSUE TITLE
conversie van lambda naar p

### ISSUE THREAD

**Issue by acolijn** [ErikHogenbirk/DMPlots#1]
Hoi Erik,
Je gebruikt p = hbar *c / lambda in plaats van h*c/lambda. 
AP

**Comment by acolijn** [comment]
in Rates.ipynb

**Comment by ErikHogenbirk** [comment]
Hoi AP, 
Voor de berekening van de de Broglie golflengte is h nodig, maar als de waarde van q r_n wordt uitgerekend die in de Helm form factor gaat is hbar nodig. De huidige implementatie is dus volgens mij correct. Ik heb een extra check gedaan en die aan het eind van het notebook toegevoegd.
